name: Dummy1

on: 
  workflow_call:
    inputs:
      TestEnv:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TestEnv:
        type: choice
        description: Select environment
        options: 
        - AutomationOrg
        - default 
      message:
        required: true
      environment:
        type: environment


jobs:
  build:
    runs-on: ubuntu-latest
    env: 
       PROVAR_HOME: ${{ github.workspace }}/ProvarHome
       
    strategy:
      fail-fast: false
      matrix:
        Plan: ["SYDATA-Purchase Order","SYDATA-Sales Order","Work Order"]
    
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H_%M_%S')"

    - name: Remove space from Test Plan
      id: TestPlanName
      run: |
        temp="${{matrix.Plan}}"	
        echo "::set-output name=TestPlanName::$(echo ${temp// /_})"
        
    - name: Remove forward slash from Test Plan
      id: PlanName
      run: |
        temp="${{ steps.TestPlanName.outputs.TestPlanName}}"	
        echo "::set-output name=PlanName::$(echo ${temp/\//-})" 
        
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8

#    - name: Clone Repository
#      uses: actions/checkout@v2
#      with:
#          ref: 'Test-Branch'
#          repository: cboyapati/rsqasampleproj
#          token: ${{ secrets.GITTOKEN }}    
 
#    - name: Send Slack Message-RootstockMfg
#      uses: archive/github-actions-slack@master
#      id: send-message
#      with:
#        slack-function: send-message
#        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
#        slack-channel: C0430LZJSG4
#        slack-text: Execution Started for Test Plan "*${{ steps.PlanName.outputs.PlanName}}*" at "*${{ steps.date.outputs.date }}*"
#
#    - name: Send "Slack Message" Result
#      run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"


    - name: Send Slack Message-Personal Slack
      uses: archive/github-actions-slack@master
      id: send-message11
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN1 }}
        slack-channel: C03KF4U7TSP
        slack-text: Automation Script execution started for ERP Version-${{ github.event.inputs.message }} ON ${{ github.event.inputs.environment }}
    - name: Send "Slack Message" Result
      run: echo "Data - ${{ steps.send-message11.outputs.slack-result }}"


    - name: Send Slack Message-Personal Slack
      uses: archive/github-actions-slack@master
      id: send-message1
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN1 }}
        slack-channel: C03KF4U7TSP
        slack-text: Execution Started for Test Plan "*${{ steps.PlanName.outputs.PlanName}}*" at "*${{ steps.date.outputs.date }}*"

    - name: Send "Slack Message" Result
      run: echo "Data - ${{ steps.send-message1.outputs.slack-result }}"

  
