name: Execute_All_API

on: 
  workflow_dispatch:
    inputs:
      Build-Version:
        required: true
      Environment:
        type: environment
  
jobs:
  Execution-Start-Slack-Notification:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.Environment }}
    
    steps:
    - name: Send Slack Message-Personal Slack
      uses: archive/github-actions-slack@master
      id: send-message
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN_RSTKMFG }}
        slack-channel: C043T1M03Q8
        slack-text: Automation Script execution started for ERP Version-${{ github.event.inputs.Build-Version }} On ${{ github.event.inputs.Environment }} by ${{ github.actor }}

    - name: Send "Slack Message" Result
      run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"
 
  workflow-1:
    needs: Execution-Start-Slack-Notification  
    uses: ./.github/workflows/Temp1.yml
    secrets: inherit
  
  workflow-2:
    if: ${{ always() }}  
    needs: workflow-1
    uses: ./.github/workflows/Temp1.yml
    secrets: inherit

  Execution-Completed-Slack-Notification:
    if: ${{ always() }}  
    needs: [workflow-1,workflow-2]
    runs-on: ubuntu-latest    
    steps:
    - name: send build completion notification
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB}) executed by ${{ github.actor }}, status is ${{ job.status }} and took ${process.env.AS_TOOK} for execution`,
            }]
          }
      env: 
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
