# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Git Summery Test1

on: 
  workflow_dispatch:
    inputs:
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg 

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Plan: ["Inventory-both","Work Order-Both","Recurring Billing","RMA","Shop Floor","System_Setup"]   
    steps:
    - name: Get Current Job Log URL 
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: build (${{matrix.Plan}})
        per_page: 100

    - name: Output Current Job Log URL
      run: |
        echo "::set-output name=URL::${{ steps.jobs.outputs.html_url }}"
        echo "${{matrix.Plan}}-JOB URL IS- ${{ steps.jobs.outputs.html_url }}"
        
        echo "## Train pull request analysis" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "|     Author(s)       |           Commits          |  Files Changed  | File Removed  |  Merge SHA |" >> $GITHUB_STEP_SUMMARY
        echo "| ------------------- | -------------------------- | --------------- |---------------|--------------|" >> $GITHUB_STEP_SUMMARY
        echo "|   @${github.actor}  |              4             |     13          |       4       |   [${{ steps.jobs.outputs.html_url }}] |" >> $GITHUB_STEP_SUMMARY
      
