name: Master_Flow3_FailureTest

on: 
  workflow_dispatch:
    inputs:
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg
jobs:
  call-workflow-11:
    name: WorkFlow-11
    uses: ./.github/workflows/Child-101.yml
    with:
      TestEnv: ${{ github.event.inputs.TestEnv }}
    secrets: inherit
  call-workflow-21:
    name: WorkFlow-21
    if: ${{ always() }}  
    needs: call-workflow-11
    uses: ./.github/workflows/Child-102.yml
    with:
      TestEnv: ${{ github.event.inputs.TestEnv }}
    secrets: inherit
